kind: ConfigMap
apiVersion: v1
metadata:
  name: configmapdemo
  namespace: prod
data:
  varA: "testingA"
  varB: "testingB"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: configmapdemo
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmapdemo
  template:
    metadata:
      labels:
        app: configmapdemo 
    spec:
      containers:
        - name: configmapdemo
          image: 'jodios/configmapdemo:latest'
          ports:
            - name: http-api
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: configmapdemo
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 300Mi
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: configmapdemo
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30420
  selector:
    app: configmapdemo