spring:
  application:
    name: configmapdemo
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: event
        strategy: refresh
      config:
        sources:
          - name: configmapdemo
configmapdemo.config:
  varA: ${varA}
  varB: ${varB}
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: 'health, info, env, refresh'
